codeuino/social-platform-donut-backend

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/pull-request-template.md

Bug raising, Feature request, Pull Request Templates

Adds templates

---

app/models/User.js
test/user.test.js

This PR updates the user test api to handle the new **about**, **company**, **website** and **location** attributes added to the user api.

Added tests for new user api

---

app/models/Comment.js
app/models/Event.js
app/models/Organisation.js
app/models/Post.js
app/models/User.js

Added schemas for an organization, users, posts, events, comments. 
fixes #58 
@devesh-verma @vaibhavdaren Please review this.

added updated schemas

---

.env.dev
app.js
app/models/User.js
bin/www
package-lock.json
package.json
test/user.test.js

Fixes #64 
Passes all the test cases.
**Screenshot**
@devesh-verma @vaibhavdaren Please review

updated test passes all the cases

---

app/models/Organisation.js
app/models/Post.js
app/models/Project.js

Fix for #70 
@devesh-verma @vaibhavdaren Please review.

added schema for projects

---

app/controllers/user.js
app/models/User.js
app/routes/user.js
package-lock.json
package.json

Fixes #81 
Added functionality to reset password
**Here is the screenshots:**
**STEP1:**
**STEP2:**
The token during screenshot was 64bytes long, reduced to 32 now (**UPDATED**)
Please review @devesh-verma @vaibhavdaren

added functionality to reset password

---

app/controllers/user.js
app/middleware/email.js
app/routes/user.js
package.json
views/emailTemplate.js

**Problem**
Github Issue Number: #54 
Describe the problem you are trying to achieve. 
Sending and Email on successful SignUp
**Before Changes Screenshot** [How was it earlier, add it here]
**After Changes Screenshot**

#54 Implements SignUp Email

---

app/controllers/user.js
app/middleware/activate.js
app/models/User.js
app/routes/auth.js
app/routes/user.js

---
name: Activate an account PR
about: implement the functionality to activate an account
title: Activate an account 
labels: Feature
assignees: @Rupeshiya
---
Github Issue Number: #83 
The issue was to implement the functionality to activate an account, if the user has not activated the account, they will not be able to log in.
They should activate the account by clicking the link sent in the email within 24hrs_
Added middleware to check if the user has activated the account or not.
Added routes to activate an account, the link sent in the email will send the request to this route. 
No UI changes
[ ] Bug fix
[ ] My Code change …

added activate account functionality

---

.env.test
app/routes/user.js
test/organisation.test.js
test/user.test.js

---
name: Org REST API TESTS
about: Tested organisatin REST API
title: ''Organisatin REST API tests"
labels: ''feature
assignees: ''@Rupeshiya
---
Github Issue Number: #116 
Adde unit tests for Org REST API_
Used jest and supertest to write unit test
No UI changes are required
[ ] Bug fix
[&check;] Small refactor
[&check;] I have squashed my commits

Tested organisatin REST API

---

app/controllers/post.js
app/models/Post.js
app/routes/post.js
app/utils/console-helper.js
test/post.test.js

---
name: Adds all the post API's
about: Implements the backend of post API's
title: 'Adds all the post API's'
labels: 'feature'
assignees: @rak-shit 
---
Github Issue Number: Fixes #101, Fixes #94 & Fixes #115
[ ] Bug fix
[x] New Feature
[x] My code follows the same style as the codebase
[x] I made PR against **development branch**
[ ] I have run the test cases locally and it's passing.
[x] I have squashed my commits

Adds all the post API's

---

app/controllers/organization.js
app/controllers/user.js
app/models/Organisation.js
app/routes/organisation.js

---
name: TRIGGER MAINTENANCE
about: Functionality to trigger maintenance mode
title: ''functionality to trigger maintenance mode
labels: ''feature
assignees: ''@Rupeshiya
---
Github Issue Number: #106 
functionality to trigger maintenance mode
REST API 
No UI chnages required 
[ ] Bug fix
[&check;] My Code change requires a change in documentation
[&check;] I have squashed my commits

(WIP) functionality to trigger maintenance mode 

---

app.js
app/controllers/comment.js
app/models/Comment.js
app/routes/comment.js
app/utils/console-helper.js
test/comment.test.js

---
title: 'Adds all comment API's'
labels: 'feature'
assignees: @rak-shit 
---
Github Issue Number: Fixes #102
[ ] Bug fix
[ x] New Feature
[ x] My code follows the same style as the codebase
[ x] I made PR against **development branch**
[ x] I have run the test cases locally and it's passing.
[ x] I have squashed my commits

Adds all comment API's

---

app/controllers/user.js
app/routes/user.js
test/user.test.js

---
title: ''
labels: ''
assignees: ''
---
Github Issue Number: #123 
The feature is not related to any problem but it's an extra feature that needs to be implemented.
So the feature is if any user of the platform want to invite any other user which on the platform so they can invite through a link, which will be used by other to get registered as a user of the platform._
One solution I can think of just generates the token using the senders token (use jsonwebtoken signed with the expiry time and sender's token). Now when the user who is invited will receive the link, let say: http://localhost:5000/invite/${token} and the link is clicked then a GET the request will be sent to the server so will catch that request and then in that request …

done with invite link functionality

---

app/controllers/organization.js
app/controllers/post.js
app/middleware/maintenance.js
app/models/Organisation.js
app/models/Post.js
app/models/User.js
app/routes/auth.js
app/routes/comment.js
app/routes/event.js
app/routes/organisation.js
app/routes/post.js
app/routes/user.js

---
title: ''
labels: ''
assignees: ''
---
Github Issue Number: #125 
We need to have backend implemented to control the organization settings by admins_
Implement the REST API to control the organization settings, so that whole organization would work according to that settings
[ ] Bug fix
[&check;] I have squashed my commits

working mechanism for triggering maintenace, updating org settings 

---

app.js
app/controllers/comment.js
app/controllers/event.js
app/controllers/post.js
app/controllers/project.js
app/controllers/user.js
app/models/Event.js
app/models/Project.js
app/models/User.js
app/routes/event.js
app/routes/index.js
app/routes/post.js
app/routes/project.js
app/routes/user.js
app/utils/paginate.js
config/mongoose.js
test/event.test.js
test/project.test.js
test/user.test.js

---
title: ''
labels: ''
assignees: ''
---
Github Issue Number: #127 #128 
**PR includes:**
1. Add pagination in the backend 
2. Add follow/unfollow functionality 
3. Block/unblock members by admins 
4. Add REST API for projects 
5. Get all the posts created by a particular user 
6. Get all the events created by a particular user 
7. Get user profile with followings and followers 
8. Upcoming events functionality
9. Updated existing test cases according to the updated codebase
_
Implement REST API for the above-mentioned problems
[&check;]Bug fix
[ &check;] My code follows the same style as the codebase
[ ] My Code change requires a …

Implementation of REST API for projects routes, paging, follow/unfollow, block/unblock etc

---

app/controllers/event.js
app/controllers/post.js
app/controllers/user.js
app/models/Event.js
app/models/Project.js
app/models/User.js
app/routes/user.js

---
title: ''
labels: ''
assignees: ''
---
Github Issue Number: #138 
When a user will set up the donut for their platform then they should be treated as an admin of the platform. Handled this case.
Also, modify backend for client-side integration like deep populate reference property to fetch those values in client-side.
Some small modifications
[ ] Bug fix
[ ] New Feature
[&check;] Small refactor
[&check;] I …

modified backend for client side integration and handle first user as admin

---

.github/workflows/image-workflow.yaml

Signed-off-by: K mehant <411843@student.nitandhra.ac.in>

Fix workflow

---

.env.dev
app.js
app/controllers/notification.js
app/controllers/organization.js
app/controllers/post.js
app/controllers/proposal.js
app/middleware/auth.js
app/models/Proposal.js
app/models/ProposalNotification.js
app/models/User.js
app/routes/notification.js
app/routes/proposal.js
app/utils/notificationTags.js
app/utils/proposal-notif-helper.js
config/fileHandlingConstants.js
config/mongoose.js
package-lock.json
package.json
test/proposal.test.js

Github Issue Number: #130 
Completed implementation of the /proposal route and test cases. (2 Remaining test cases for file attachment and fetching org related proposals.)
**Generated docs** - [Link](https://documenter.getpostman.com/view/7312043/SzzdCLPr)
[ ] Bug fix
[x] New Feature
[x] My code follows the same style as the codebase
[x] My Code change requires a change in documentation
[x] I have updated the Readme accordingly
[x] I made PR against **development branch**
[x] I have run the test cases locally and it's passing.
[x] I have squashed my commits

Implementation of /proposal route and proposal test cases

---

app/controllers/organization.js

---
title: ''
labels: ''
assignees: ''
---
Github Issue Number: #
Describe the problem you are trying to achieve. Please provide in detail_
How did you solve this problem?
**Before Changes Screenshot** [How was it earlier, add it here]
**After Changes Screenshot** [How it looks now, add it here]
[ ] Bug fix
[ ] New Feature
[ ] My code follows the same style as the codebase
[ ] I made PR against **development branch**
[ ] I have run the test cases locally and it's passing.
[ ] I have squashed my commits

fixing org creation issue

---

app.js
app/controllers/analytics.js
app/routes/analytics.js
config/gAnalytics.js
package-lock.json
package.json

As discussed in the previous meeting there was an issue with authenticating _all_ the users of the application within the clientside implementation at https://github.com/codeuino/social-platform-donut-frontend/pull/529. 
How did you solve this problem?
This is fixed in this PR with the use of a google service account. Any user hitting the endpoints introduced in this PR would be able to get a response with the required details without any issue

Moving Google Analytics requests to backend

---

app/controllers/post.js
app/models/Post.js
app/routes/post.js

Github Issue Number: #165 
**After Changes Screenshot**

Changes required for reactions

---

app.js
package-lock.json

Reverts codeuino/social-platform-donut-backend#153

Revert "Adding code to prevent attacks"

---

.env.dev
app.js
app/controllers/activity.js
app/controllers/auth.js
app/controllers/comment.js
app/controllers/event.js
app/controllers/organization.js
app/controllers/post.js
app/controllers/project.js
app/controllers/user.js
app/middleware/activity.js
app/models/Activity.js
app/routes/activity.js
app/routes/organisation.js
app/utils/activity-helper.js
app/utils/collections.js
config/redis.js
package-lock.json
package.json
test/organisation.test.js
test/user.test.js

---
title: ''
labels: ''
assignees: ''
---
Github Issue Number: #150 
As of now, there is no backend implemented to track user activity on to the platform _
Implement the backend using redis to track user activity on to the platform
[ ] Bug fix
[ ] I have squashed my commits

User activity tracker using redis

---

app/middleware/rateLimiter.js
test/organisation.test.js

---
title: ''
labels: ''
assignees: ''
---
Github Issue Number: #
Increasing the rate was required as there are lots of requests needs to made from client side
Increase the rate limit request rate
[&check;] Bug fix
[ ] New Feature
[[&check;] Small refactor
[&check;] I have squashed my commits

Minor issue rate fix

---

test/user.test.js

Post GSOC conflict fix
